name: NestJS Build and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Install @nrwl/nx-linux-x64-gnu
        run: npm install @nrwl/nx-linux-x64-gnu

      - name: Build
        run: npm run build:api

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ./Dockerfile
          build-args: |
            NODE_VERSION=${{ secrets.NODE_VERSION }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "events-manager-api-cd"
          heroku_email: "fremen1990@gmail.com"
          container_registry: "registry.heroku.com"
          image_name: "events-manager-api-cd"
          dockerfile_path: "./Dockerfile"
          build_dir: "dist/apps/api"
