name: Heroku CD
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - user: akhilenshns/heroku-deploy@v3.12.12
            with:
               branch: main
               heroku_api_key: ${{secrets.HEROKU_API_KEY}}
               heroku_app_name: "events-manager-api-cd"
               heroku_email: "fremen1990@gmail.com"
