name: Heroku CD
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Install dependencies
            run: npm ci
          - name: Install @nrwl/nx-linux-x64-gnu
            run: npm install @nrwl/nx-linux-x64-gnu
          - name: Deploy to Heroku
            uses: AkhileshNS/heroku-deploy@v3.12.13
            with:
              branch: main
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: "events-manager-api-cd"
              heroku_email: "fremen1990@gmail.com"
