name: Tests Coverage Deploy
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          sha: ${{ github.sha }}

      - name: Install dependencies
        run: npm ci

      - name: Install @nrwl/nx-linux-x64-gnu
        run: npm install @nrwl/nx-linux-x64-gnu

      - name: Format
        #        run: npm run format:check
        run: npx nx affected --target=format:check --parallel=3 --projects=web,api

      - name: Lint
        run: npx nx affected --target=lint --parallel=3 --projects=web,api

      - name: Unit Tests Web
        run: npx nx affected --target=test --parallel=3 --projects=web
        continue-on-error: true

      - name: Unit Tests Api
        run: npx nx affected --target=test --parallel=3 --projects=api

      #      - name: E2E Tests
      #        run: npx nx affected --target=e2e --parallel=3 --configuration=ci --projects=web,api

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          parallel: true
          path-to-lcov: coverage/apps/api/lcov.info

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          parallel-finished: true
