name: Storybook Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install @nrwl/nx-linux-x64-gnu
        run: npm install @nrwl/nx-linux-x64-gnu

      - name: Build Storybook
        run: npx nx build-storybook web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist/storybook/web
          publish_branch: gh-pages
#          cname: my-custom-domain.com
#          base_url: https://my-custom-domain.com/my-app
